apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: europe-central2-docker.pkg.dev/clc3v2-mk-nn-jp/clc/my-app:latest # Deine Container-Registry
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
