apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: gcr.io/clc3-mm-nn-jp/static-site:latest  # Deine Container-Registry
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
