apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - clcdummyclient-deployment.yaml
  - clcdummydb-deployment.yaml
  - clcdummydb-pvc.yaml

images:
  - name: europe-central2-docker.pkg.dev/clc3v2-mk-nn-jp/clc/static-site
    newName: europe-central2-docker.pkg.dev/clc3v2-mk-nn-jp/clc/static-site
    newTag: latest

namespace: default

