apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - deployment.yaml        # Dein Streamlit Deployment
  - service.yaml           # Dein Streamlit Service
  - minio-deployment.yaml  # MinIO Deployment
  - minio-service.yaml     # MinIO Service

images:
  - name: 
    newName: europe-central2-docker.pkg.dev/clc3v2-mk-nn-jp/clc/static-site
    newTag: latest

namespace: default

