apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

namespace: mynamespace

# Example of applying a patch
patchesStrategicMerge:
  - deployment-patch.yaml

# Example of setting replicas
commonLabels:
  app: static-site

images:
  - name: 
    newName: europe-central2-docker.pkg.dev/clc3v2-mk-nn-jp/my-repo/my-app
    newTag: latest

# Example of adding a ConfigMap
configMapGenerator:
  - name: app-config
    literals:
      - APP_ENV=production
