apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - deployment.yaml
  - service.yaml

images:
  - name: 
    newName: europe-central2-docker.pkg.dev/clc3v2-mk-nn-jp/clc/static-site
    newTag: latest

namespace: default

