apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

images:
  - name: 
    newName: europe-central2-docker.pkg.dev/clc3v2-mk-nn-jp/my-repo/my-app
    newTag: latest

